spring.application.name=jobportal
server.port=8080


spring.datasource.url=jdbc:postgresql://localhost:5433/jobportal_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=change-this-to-a-long-secret-key-for-development-1234567890
app.jwt.access-token-expiration=3600000
